spring.datasource.url=jdbc:postgresql://dpg-d85ktf7dl75s738v40f0-a:5432/nexora_db_uqom?TimeZone=UTC
spring.datasource.username=nexora_db_uqom_user
spring.datasource.password=NwREPILLWWtCSuWxvn1wC9XOH5yCOmL5
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8080
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=narlaravindra63@gmail.com
spring.mail.password=hsfwsxgqizmwgtdi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
