spring.datasource.url=jdbc:postgresql://localhost:5434/nexora?TimeZone=UTC
spring.datasource.username=postgres
spring.datasource.password=nexora123
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8080

# Gmail config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=narlaravindra63@gmail.com
spring.mail.password=hsfwsxgqizmwgtdi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
